// Shared id helpers for the catalog scripts. Pricing does NOT live here:
// the official Ollama Cloud rate card (catalog/pricing.json) is the only
// pricing source, regenerated by the manual update-pricing workflow —
// the catalog resolver is price-blind.

// Canonical split of a model id `family[:tag]` (CONTEXT.md: "family" is the
// term; never "base"). Shared by resolve- and update-catalog.
export const familyOf = (id: string) => id.split(":")[0];
export const tagOf = (id: string) => (id.includes(":") ? id.split(":")[1] : "");

// models.dev remains the seed for catalog SPECS (maxOutput, reasoningOptions,
// releaseDate) — never for pricing.
export const MODELS_DEV_URL = "https://models.dev/api.json";
